# LSP configuration

# bash
# css/scss
# docker-compose
# docker-file
# go
# graphql
# html
# javascript/typescript/jsx/tsx
# json
# lua
# markdown
# python
# rust
# sql
# toml

# vue
[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "C:\\Users\\Mauri\\AppData\\Roaming\\npm\\node_modules\\@vue\\language-server"
languages = ["vue"]

# yaml

# DEBUGGER Configuration

# dlv debugger
# lldb-dap
